import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import Container from "react-bootstrap/Container";
import Navbar from "react-bootstrap/Navbar";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sanity-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar bg="dark" expand="lg">
        <Container>
          <Navbar.Brand
            style={{
              color: "white",
            }}
            href="#home"
          >
            Sanity Blog
          </Navbar.Brand>
        </Container>
      </Navbar>
    </div>
  );
};

export default Home;
